//! Golden tests of the stateless-model refactor (2026-09-14): every
//! estimator, on every model, must reproduce the outputs recorded from the
//! previous implementation — where a model carried its own trajectory and
//! noisy observation — now that the reference is generated outside the
//! model and the observations are passed to the observers step by step.
//!
//! `golden/stateful.json` was written by a throw-away program running the
//! old code (job runners and the particle system); each case below rebuilds
//! the same twin experiment with the new API and compares field by field.
//! The Gauss–Legendre models and the lamppost are compared *bit for bit*;
//! the spring's reference is now generated by the transition matrix T
//! (the discrete flow the observers use) instead of the old `forward()`'s
//! LU solve of the same midpoint step, so its cases are compared to 1e-9
//! relative — round-off, not a change of the algorithm.

use ode_models::models::kepler::perihelion_state;
use ode_models::models::kepler_mu::augmented_state;
use ode_models::models::*;
use ode_models_spec::noise::NoiseModel;
use ode_models_spec::progress::Progress;
use ode_models_spec::reference::{Reference, Walk};
use ode_models_spec::spec::{ModelSpec, TwinSpec};
use ode_observers::jobs::*;
use ode_observers::methods::fleming_viot::{ParticleParams, ParticleSystem};
use serde_json::Value;
use std::f64::consts::PI;

fn golden() -> serde_json::Map<String, Value> {
    let text = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/golden/stateful.json")).unwrap();
    serde_json::from_str::<Value>(&text).unwrap().as_object().unwrap().clone()
}

/// Compare a serializable value with the recorded one, recursively, to a
/// relative tolerance (`0.0` = bit for bit). The tolerance is relative to
/// the larger of the two values *and* of the field's overall magnitude, so
/// that a value of 1e-14 in a density whose maximum is 1 (a box corner,
/// where the interpolation's round-off dominates) is compared absolutely.
fn check<T: serde::Serialize>(case: &str, field: &str, actual: &T, expected: &Value, tol: f64) {
    fn magnitude(v: &Value) -> f64 {
        match v {
            Value::Array(a) => a.iter().map(magnitude).fold(0.0, f64::max),
            Value::Number(n) => n.as_f64().unwrap().abs(),
            _ => 0.0,
        }
    }
    fn go(path: &str, a: &Value, e: &Value, tol: f64, scale: f64) {
        match (a, e) {
            (Value::Array(a), Value::Array(e)) => {
                assert_eq!(a.len(), e.len(), "{path}: length {} vs {}", a.len(), e.len());
                for (i, (x, y)) in a.iter().zip(e).enumerate() {
                    go(&format!("{path}[{i}]"), x, y, tol, scale);
                }
            }
            (Value::Number(a), Value::Number(e)) => {
                let (a, e) = (a.as_f64().unwrap(), e.as_f64().unwrap());
                let ok = if tol == 0.0 {
                    a.to_bits() == e.to_bits() || a == e
                } else {
                    (a - e).abs() <= tol * a.abs().max(e.abs()).max(scale)
                };
                assert!(ok, "{path}: {a:e} vs golden {e:e}");
            }
            (Value::Null, Value::Null) => {}
            (Value::Bool(a), Value::Bool(e)) => assert_eq!(a, e, "{path}"),
            _ => panic!("{path}: {a} vs {e}"),
        }
    }
    let actual = serde_json::to_value(actual).unwrap();
    go(&format!("{case}.{field}"), &actual, expected, tol, magnitude(expected));
}

/// A configuration as the recording made it: the defaults from eleven
/// copies of `x0` (not from the real trajectory).
fn cfg_from(labels: &[&str], periodic: Vec<Option<(f64, f64)>>, pairs: &[(usize, usize)], x0: &[f64]) -> FilterConfig {
    FilterConfig::defaults(labels.iter().map(|s| s.to_string()).collect(), periodic, pairs, &vec![x0.to_vec(); 11])
}

fn twin(model: ModelSpec, x0: &[f64], dt: f64, steps: usize, noise: NoiseModel, seed: u64, walk: Option<Walk>) -> TwinSpec {
    TwinSpec { model, x0: x0.to_vec(), dt, steps, noise, seed, walk }
}

const SPRING_TOL: f64 = 1e-9;

#[test]
fn spring_filter_tracker_window_and_particles() {
    let g = golden();
    let p = Progress::default();
    let dt = 0.02;
    let model = ModelSpec::Spring { n: 1, rho: 1.0, a: 1.0, obs: 0 };
    let noise = NoiseModel::Gaussian { std: 0.01 };
    let mut cfg = cfg_from(&["y_1", "v_1"], vec![None; 2], &[(0, 1)], &[0.15, 0.0]);
    for v in &mut cfg.vars {
        v.sigma = 5.0;
        v.half_width = 0.8;
    }
    cfg.n_snapshots = 3;

    let c = &g["spring_filter"];
    let r = twin(model.clone(), &[0.15, 0.0], dt, 20, noise, 1000, None).reference(&p);
    check("spring_filter", "reference", &r.states, &c["reference"], SPRING_TOL);
    check("spring_filter", "observations", &r.observations, &c["observations"], SPRING_TOL);
    let out = run_filter_spec(&model, &r, &cfg, &p);
    check("spring_filter", "estimates", &out.estimates, &c["estimates"], SPRING_TOL);
    check("spring_filter", "marginal", &out.marginals.last().unwrap()[0], &c["marginal"], SPRING_TOL);
    check("spring_filter", "saved_steps", &out.saved_steps, &c["saved_steps"], 0.0);
    check("spring_filter", "axes", &out.axes, &c["axes"], 0.0);

    let c = &g["spring_tracker"];
    let r = twin(model.clone(), &[0.15, 0.0], dt, 200, noise, 1000, None).reference(&p);
    let out = run_tracker_spec(&model, &r, &cfg, &p);
    check("spring_tracker", "estimates", &out.estimates, &c["estimates"], SPRING_TOL);
    check("spring_tracker", "covariances", &out.covariances, &c["covariances"], SPRING_TOL);
    check("spring_tracker", "reference", &out.reference, &c["reference"], SPRING_TOL);

    let c = &g["spring_window"];
    let r = twin(model.clone(), &[0.15, 0.0], dt, 100, noise, 1000, None).reference(&p);
    let out = run_box_spec(&model, &r, &cfg, &p);
    check("spring_window", "estimates", &out.window.estimates, &c["estimates"], SPRING_TOL);
    check("spring_window", "centers", &out.centers, &c["centers"], SPRING_TOL);
    check("spring_window", "marginal", &out.window.marginals.last().unwrap()[0], &c["marginal"], SPRING_TOL);
    check("spring_window", "reference", &out.window.reference, &c["reference"], SPRING_TOL);

    let c = &g["spring_particles"];
    let r = twin(model, &[0.15, 0.0], dt, 30, noise, 1000, None).reference(&p);
    let pp = ParticleParams::<2> {
        n_particles: 50,
        center: [0.15, 0.0],
        sigma: [5.0; 2],
        domain: [(-0.5, 0.5); 2],
        periodic: [false; 2],
        eps: 0.01,
        q_diag: [1.0; 2],
        noise_scale: 1.0,
        gamma: 1.0,
        seed: 11,
    };
    let mut ps = ParticleSystem::<2, _>::new(SpringSystem::new(1, 1.0, 1.0, dt, |x: &[f64]| x[0]), pp);
    for y in &r.observations[..30] {
        ps.forward(y);
    }
    check("spring_particles", "positions", &ps.positions(), &c["positions"], SPRING_TOL);
    check("spring_particles", "budgets", &ps.budgets(), &c["budgets"], 0.0);
    check("spring_particles", "spent", &ps.spent(), &c["spent"], SPRING_TOL);
    assert_eq!(ps.births() as u64, c["births"].as_u64().unwrap());
    check("spring_particles", "reference", &r.states, &c["reference"], SPRING_TOL);
}

#[test]
fn kepler_bearing_tracker_with_ar1_noise() {
    let g = golden();
    let c = &g["kepler_tracker"];
    let p = Progress::default();
    let x0 = perihelion_state(0.5);
    let model = ModelSpec::Kepler { params: KeplerParams { mu: 1.2, softening: 0.1 }, observation: KeplerObservation::Bearing };
    let r = twin(model.clone(), &x0, 0.02, 100, NoiseModel::Ar1 { std: 0.05, tau: 0.5 }, 4002, None).reference(&p);
    check("kepler_tracker", "reference", &r.states, &c["reference"], 0.0);
    check("kepler_tracker", "observations", &r.observations, &c["observations"], 0.0);
    let mut cfg = cfg_from(&["q_1", "q_2", "p_1", "p_2"], vec![None; 4], &[(0, 1)], &x0);
    for v in &mut cfg.vars {
        v.sigma = 2.0;
    }
    let out = run_tracker_spec(&model, &r, &cfg, &p);
    check("kepler_tracker", "estimates", &out.estimates, &c["estimates"], 0.0);
    check("kepler_tracker", "covariances", &out.covariances, &c["covariances"], 0.0);
}

#[test]
fn pendulum_filter_with_periodic_angles_and_tip_noise() {
    let g = golden();
    let c = &g["pendulum_filter"];
    let p = Progress::default();
    let x0 = [1.5, 1.4, 0.0, 0.0];
    let model = ModelSpec::Pendulum { params: PendulumParams::default() };
    let r = twin(model.clone(), &x0, 0.01, 5, NoiseModel::Gaussian { std: 0.01 }, 2000, None).reference(&p);
    check("pendulum_filter", "reference", &r.states, &c["reference"], 0.0);
    check("pendulum_filter", "observations", &r.observations, &c["observations"], 0.0);
    let mut cfg = cfg_from(&["q_1", "q_2", "p_1", "p_2"], vec![Some((-PI, PI)), Some((-PI, PI)), None, None], &[(0, 2)], &x0);
    for v in &mut cfg.vars {
        v.sigma = 1.0;
        v.n_el = 3;
        v.p_ord = 2;
        if !v.periodic {
            v.domain = (-3.0, 3.0);
        }
    }
    cfg.n_snapshots = 2;
    let out = run_filter_spec(&model, &r, &cfg, &p);
    check("pendulum_filter", "estimates", &out.estimates, &c["estimates"], 0.0);
    check("pendulum_filter", "marginal", &out.marginals.last().unwrap()[0], &c["marginal"], 0.0);
}

#[test]
fn lamppost_filter_with_a_walking_reference() {
    let g = golden();
    let c = &g["lamppost_filter"];
    let p = Progress::default();
    let model = ModelSpec::Lamppost;
    let r = twin(model.clone(), &[0.0, 1.0], 0.05, 10, NoiseModel::Gaussian { std: 0.05 }, 7100, Some(Walk { std: 0.1, seed: 7000 }))
        .reference(&p);
    check("lamppost_filter", "reference", &r.states, &c["reference"], 0.0);
    check("lamppost_filter", "observations", &r.observations, &c["observations"], 0.0);
    let mut cfg = cfg_from(&["x", "y"], vec![None; 2], &[(0, 1)], &[0.0, 1.0]);
    for v in &mut cfg.vars {
        v.sigma = 0.0;
        v.half_width = 0.8;
        v.domain = (-2.0, 2.0);
        v.n_el = 8;
        v.p_ord = 2;
    }
    cfg.n_snapshots = 3;
    cfg.eps = 0.05;
    let out = run_filter_spec(&model, &r, &cfg, &p);
    check("lamppost_filter", "estimates", &out.estimates, &c["estimates"], 0.0);
    check("lamppost_filter", "marginal", &out.marginals.last().unwrap()[0], &c["marginal"], 0.0);
}

#[test]
fn kepler_mu_lorenz_and_rod_trackers_and_spring_mass_filter() {
    let g = golden();
    let p = Progress::default();

    let c = &g["kepler_mu_tracker"];
    let x0 = augmented_state(perihelion_state(0.3), 0.1);
    let model = ModelSpec::KeplerMu { params: KeplerMuParams::default(), observation: KeplerObservation::Q1 };
    let r = twin(model.clone(), &x0, 0.01, 30, NoiseModel::Uniform { half_width: 0.02 }, 5000, None).reference(&p);
    check("kepler_mu_tracker", "reference", &r.states, &c["reference"], 0.0);
    check("kepler_mu_tracker", "observations", &r.observations, &c["observations"], 0.0);
    let mut cfg = cfg_from(&["q_1", "q_2", "p_1", "p_2", "θ"], vec![None; 5], &[(0, 4)], &x0);
    for (d, v) in cfg.vars.iter_mut().enumerate() {
        v.sigma = if d < 4 { 1000.0 } else { 1.0 };
        v.x0 = if d < 4 { x0[d] } else { 0.0 };
        v.q = 0.0;
    }
    let out = run_tracker_spec(&model, &r, &cfg, &p);
    check("kepler_mu_tracker", "estimates", &out.estimates, &c["estimates"], 0.0);

    let c = &g["lorenz_tracker"];
    let x0 = [-3.716171, -4.204785, 20.339103];
    let model = ModelSpec::Lorenz { params: LorenzParams::default(), observation: LorenzObservation::X };
    let r = twin(model.clone(), &x0, 0.01, 50, NoiseModel::Gaussian { std: 0.1 }, 5001, None).reference(&p);
    check("lorenz_tracker", "reference", &r.states, &c["reference"], 0.0);
    check("lorenz_tracker", "observations", &r.observations, &c["observations"], 0.0);
    let mut cfg = cfg_from(&["x", "y", "z"], vec![None; 3], &[(0, 1)], &x0);
    for v in &mut cfg.vars {
        v.sigma = 1.0;
        v.x0 += 1.0;
    }
    let out = run_tracker_spec(&model, &r, &cfg, &p);
    check("lorenz_tracker", "estimates", &out.estimates, &c["estimates"], 0.0);

    let c = &g["spring_mass_filter"];
    let x0 = [0.0, 0.15, 0.0, 0.0, 0.3];
    let model = ModelSpec::SpringMass { n: 2, params: SpringMassParams::default(), obs: 1 };
    let r = twin(model.clone(), &x0, 0.02, 3, NoiseModel::Gaussian { std: 0.01 }, 6021, None).reference(&p);
    check("spring_mass_filter", "reference", &r.states, &c["reference"], 0.0);
    check("spring_mass_filter", "observations", &r.observations, &c["observations"], 0.0);
    let mut cfg = cfg_from(&["y_1", "y_2", "v_1", "v_2", "θ"], vec![None; 5], &[(0, 4)], &x0);
    for (d, v) in cfg.vars.iter_mut().enumerate() {
        v.sigma = 1.0;
        v.n_el = 2;
        v.p_ord = 2;
        if d == 4 {
            v.domain = (-1.0, 1.0);
            v.q = 0.0;
            v.x0 = 0.0;
        }
    }
    cfg.n_snapshots = 2;
    let out = run_filter_spec(&model, &r, &cfg, &p);
    check("spring_mass_filter", "estimates", &out.estimates, &c["estimates"], 0.0);
    check("spring_mass_filter", "marginal", &out.marginals.last().unwrap()[0], &c["marginal"], 0.0);

    let c = &g["pendulum_rod_tracker"];
    let x0 = [2.453, -2.7727, 0.0, 0.0];
    let model = ModelSpec::PendulumRod { params: PendulumRodParams::default() };
    let r = twin(model.clone(), &x0, 0.01, 40, NoiseModel::Gaussian { std: 0.02 }, 3000, None).reference(&p);
    check("pendulum_rod_tracker", "reference", &r.states, &c["reference"], 0.0);
    check("pendulum_rod_tracker", "observations", &r.observations, &c["observations"], 0.0);
    let mut cfg = cfg_from(&["q_1", "q_2", "p_1", "p_2"], vec![Some((-PI, PI)), Some((-PI, PI)), None, None], &[(0, 2)], &x0);
    for v in &mut cfg.vars {
        v.sigma = 1.0;
    }
    let out = run_tracker_spec(&model, &r, &cfg, &p);
    check("pendulum_rod_tracker", "estimates", &out.estimates, &c["estimates"], 0.0);
}

/// The generator's `Reference` is what the old models produced, so the
/// `Reference::twin` of a model equals a hand-run of its flow.
#[test]
fn reference_twin_is_the_flow_iterated() {
    let sys = LorenzSystem::new(0.01, LorenzObservation::Y);
    let r = Reference::twin(&sys, [1.0, 1.0, 1.0], 20, NoiseModel::None, 0, None, &Progress::default());
    let mut x = [1.0, 1.0, 1.0];
    for n in 0..20 {
        x = sys.flow(&x);
        assert_eq!(r.states[n + 1], x.to_vec());
        assert_eq!(r.observations[n + 1], vec![x[1]]);
    }
}
